//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtistsTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArtistsTBL()
        {
            this.SongsTBL = new HashSet<SongsTBL>();
        }
    
        public int id { get; set; }
        public Nullable<int> art1 { get; set; }
        public Nullable<int> art2 { get; set; }
        public Nullable<int> art3 { get; set; }
        public Nullable<int> art4 { get; set; }
        public Nullable<int> art5 { get; set; }
        public Nullable<int> art6 { get; set; }
        public Nullable<int> art7 { get; set; }
        public Nullable<int> art8 { get; set; }
        public Nullable<int> art9 { get; set; }
        public Nullable<int> art10 { get; set; }
    
        public virtual ArtistsNameTBL ArtistsNameTBL { get; set; }
        public virtual ArtistsNameTBL ArtistsNameTBL1 { get; set; }
        public virtual ArtistsNameTBL ArtistsNameTBL2 { get; set; }
        public virtual ArtistsNameTBL ArtistsNameTBL3 { get; set; }
        public virtual ArtistsNameTBL ArtistsNameTBL4 { get; set; }
        public virtual ArtistsNameTBL ArtistsNameTBL5 { get; set; }
        public virtual ArtistsNameTBL ArtistsNameTBL6 { get; set; }
        public virtual ArtistsNameTBL ArtistsNameTBL7 { get; set; }
        public virtual ArtistsNameTBL ArtistsNameTBL8 { get; set; }
        public virtual ArtistsNameTBL ArtistsNameTBL9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SongsTBL> SongsTBL { get; set; }
    }
}
