//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtistsToSongsTBL
    {
        public int id { get; set; }
        public Nullable<int> songId { get; set; }
        public Nullable<int> artistId { get; set; }
        public Nullable<int> jobId { get; set; }
    
        public virtual ArtistsTBL ArtistsTBL { get; set; }
        public virtual JobTBL JobTBL { get; set; }
        public virtual SongsTBL SongsTBL { get; set; }
    }
}
