//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommitsToSongsTBL
    {
        public int id { get; set; }
        public Nullable<int> songId { get; set; }
        public string name { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<bool> tested { get; set; }
    
        public virtual SongsTBL SongsTBL { get; set; }
    }
}
