//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PinnedItemsTBL
    {
        public int id { get; set; }
        public Nullable<int> userId { get; set; }
        public string title { get; set; }
        public string image { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> count_like { get; set; }
        public Nullable<int> count_views { get; set; }
    
        public virtual UsersTBL UsersTBL { get; set; }
    }
}
