//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaylistsTBL1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlaylistsTBL1()
        {
            this.SongsToPlaylistsTBLs = new HashSet<SongsToPlaylistsTBL1>();
        }
    
        public int id { get; set; }
        public Nullable<int> userId { get; set; }
        public string name { get; set; }
    
        public virtual UsersTBL1 UsersTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SongsToPlaylistsTBL1> SongsToPlaylistsTBLs { get; set; }
    }
}
