//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SongsTBL1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SongsTBL1()
        {
            this.ReportsTBLs = new HashSet<ReportsTBL1>();
            this.SongsToPlaylistsTBLs = new HashSet<SongsToPlaylistsTBL1>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string fileLocation { get; set; }
        public string type { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<long> count { get; set; }
        public Nullable<int> singerId { get; set; }
        public Nullable<int> liked { get; set; }
        public Nullable<int> unliked { get; set; }
        public Nullable<int> tagsId { get; set; }
        public Nullable<int> albumId { get; set; }
        public string title { get; set; }
        public string image { get; set; }
        public string content { get; set; }
    
        public virtual AlbumsTBL1 AlbumsTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportsTBL1> ReportsTBLs { get; set; }
        public virtual SingersTBL1 SingersTBL { get; set; }
        public virtual TagsTBL1 TagsTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SongsToPlaylistsTBL1> SongsToPlaylistsTBLs { get; set; }
    }
}
