//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SongsToUserPlaylistsTBL
    {
        public int id { get; set; }
        public Nullable<int> playlistId { get; set; }
        public Nullable<int> songId { get; set; }
    
        public virtual SongsTBL SongsTBL { get; set; }
        public virtual UserPlaylistsTBL UserPlaylistsTBL { get; set; }
    }
}
