//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriptionTBL
    {
        public int id { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> singerId { get; set; }
    
        public virtual SingersTBL SingersTBL { get; set; }
        public virtual UsersTBL UsersTBL { get; set; }
    }
}
