//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagsTBL1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TagsTBL1()
        {
            this.ArticlesBTLs = new HashSet<ArticlesBTL1>();
            this.SongsTBLs = new HashSet<SongsTBL1>();
        }
    
        public int id { get; set; }
        public Nullable<int> tag1 { get; set; }
        public Nullable<int> tag2 { get; set; }
        public Nullable<int> tag3 { get; set; }
        public Nullable<int> tag4 { get; set; }
        public Nullable<int> tag5 { get; set; }
        public Nullable<int> tag6 { get; set; }
        public Nullable<int> tag7 { get; set; }
        public Nullable<int> tag8 { get; set; }
        public Nullable<int> tag9 { get; set; }
        public Nullable<int> tag10 { get; set; }
        public Nullable<int> tag11 { get; set; }
        public Nullable<int> tag12 { get; set; }
        public Nullable<int> tag13 { get; set; }
        public Nullable<int> tag14 { get; set; }
        public Nullable<int> tag15 { get; set; }
        public Nullable<int> tag16 { get; set; }
        public Nullable<int> tag17 { get; set; }
        public Nullable<int> tag18 { get; set; }
        public Nullable<int> tag19 { get; set; }
        public Nullable<int> tag20 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticlesBTL1> ArticlesBTLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SongsTBL1> SongsTBLs { get; set; }
        public virtual TagNameTBL1 TagNameTBL { get; set; }
        public virtual TagNameTBL1 TagNameTBL1 { get; set; }
        public virtual TagNameTBL1 TagNameTBL2 { get; set; }
        public virtual TagNameTBL1 TagNameTBL3 { get; set; }
        public virtual TagNameTBL1 TagNameTBL4 { get; set; }
        public virtual TagNameTBL1 TagNameTBL5 { get; set; }
        public virtual TagNameTBL1 TagNameTBL6 { get; set; }
        public virtual TagNameTBL1 TagNameTBL7 { get; set; }
        public virtual TagNameTBL1 TagNameTBL8 { get; set; }
        public virtual TagNameTBL1 TagNameTBL9 { get; set; }
        public virtual TagNameTBL1 TagNameTBL10 { get; set; }
        public virtual TagNameTBL1 TagNameTBL11 { get; set; }
        public virtual TagNameTBL1 TagNameTBL12 { get; set; }
        public virtual TagNameTBL1 TagNameTBL13 { get; set; }
        public virtual TagNameTBL1 TagNameTBL14 { get; set; }
        public virtual TagNameTBL1 TagNameTBL15 { get; set; }
        public virtual TagNameTBL1 TagNameTBL16 { get; set; }
        public virtual TagNameTBL1 TagNameTBL17 { get; set; }
        public virtual TagNameTBL1 TagNameTBL18 { get; set; }
        public virtual TagNameTBL1 TagNameTBL19 { get; set; }
    }
}
