//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagsToArticlesTBL
    {
        public int id { get; set; }
        public Nullable<int> tagId { get; set; }
        public Nullable<int> articleId { get; set; }
    
        public virtual ArticlesTBL ArticlesTBL { get; set; }
        public virtual TagsTBL TagsTBL { get; set; }
    }
}
