//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagsTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TagsTBL()
        {
            this.ArticlesBTL = new HashSet<ArticlesBTL>();
            this.SongsTBL = new HashSet<SongsTBL>();
        }
    
        public int id { get; set; }
        public string tag1 { get; set; }
        public string tag2 { get; set; }
        public string tag3 { get; set; }
        public string tag4 { get; set; }
        public string tag5 { get; set; }
        public string tag6 { get; set; }
        public string tag7 { get; set; }
        public string tag8 { get; set; }
        public string tag9 { get; set; }
        public string tag10 { get; set; }
        public string tag11 { get; set; }
        public string tag12 { get; set; }
        public string tag13 { get; set; }
        public string tag14 { get; set; }
        public string tag15 { get; set; }
        public string tag16 { get; set; }
        public string tag17 { get; set; }
        public string tag18 { get; set; }
        public string tag19 { get; set; }
        public string tag20 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticlesBTL> ArticlesBTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SongsTBL> SongsTBL { get; set; }
    }
}
