//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsersTBL()
        {
            this.PlaylistsTBLs = new HashSet<PlaylistsTBL>();
            this.SingerSearchingToUserTBLs = new HashSet<SingerSearchingToUserTBL>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string mail { get; set; }
        public string password { get; set; }
        public Nullable<bool> type { get; set; }
        public Nullable<bool> repeat { get; set; }
        public Nullable<bool> coincidental { get; set; }
        public Nullable<bool> newsletter { get; set; }
        public Nullable<bool> saveLike { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlaylistsTBL> PlaylistsTBLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SingerSearchingToUserTBL> SingerSearchingToUserTBLs { get; set; }
    }
}
